version: '3.8'

services:
  open-webui:
    image: registry.cn-shenzhen.aliyuncs.com/valdanito/open-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui_data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://host.docker.internal:11434/api'
      - 'WEBUI_SECRET_KEY='
      - 'HF_ENDPOINT=https://hf-mirror.com'
    extra_hosts:
      - host.docker.internal:host-gateway

